# Generated by Django 3.0.7 on 2020-06-17 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20190925_0220'),
        ('products', '0003_auto_20200611_1749'),
    ]

    operations = [
    ]
