# Generated by Django 3.0.7 on 2020-06-17 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_merge_20200617_2046'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
